version: '3.3'
services:
  image-profiler:
    build: ./app
    command: nodemon index.js
    volumes:
      - ./app:/app
    ports:
      - 4000:4000
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./usr/share/elasticsearch/data
    ports:
      - 9200:9200