version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.publish_host=127.0.0.1
      - reindex.remote.whitelist=*:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./usr/share/elasticsearch/data
    ports:
      - 9200:9200